### ISSUE TITLE
What are that xid pakets  

### ISSUE THREAD

**Issue by wrenix** [Sn0w3y/NEP-Inverter-Reversing#6]
does anybody know, what that XID paket from network?

Here an output i captured with `tcpdump`:
```
e8:xx:xx:xx:xx:xx > ff:ff:ff:ff:ff:ff Null Unnumbered, xid, Flags [Response], length 6: 01 02
```

**Comment by Sn0w3y** [comment]
Given the broad nature of the MAC broadcast address and the mention of a response flag, this could be part of a discovery process, where one device is broadcasting a request to identify other devices on the network, and this packet is a response to such a request. This is common in many network protocols for establishing initial communication or for network services discovery.

I guess it is unrelated to values of the Inverter thus i will close this Issue if it is okay for you as i guessx the Inverter is only discovering Devices in the Network (or trying to) ;)
